### ISSUE TITLE
"Unable to retrieve content" when looking a job files

### ISSUE THREAD

**Issue by stevenhorsman-ibm** [zowe/explorer-jes#10]
When looking at a job steps that is a data set I get the above error.
Looking that network it had 404 on https://winmvs3b.hursley.ibm.com:7443/Atlas/api/jobs/COPY/ids/JOB14561/steps/1/dds/3/datasets/STEVENH.DEMO.JCL(INPUT).

Looking at the api code there doesn't seem to be a path for this request - should we be calling a dataset api to get this?

**Comment by jordanCain** [comment]
Resolved in #12
