### ISSUE TITLE
Filters: job filter prefix can't select 2nd item

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/explorer-jes#112]
I tried entering 2 values separately in the 'prefix' field, but when I returned to select a stored value from my list, I could not select the second one.  
![image](https://user-images.githubusercontent.com/36740892/67191635-dcde5a80-f3e9-11e9-8e90-8e90bebba7bb.png)

**Comment by jordanCain** [comment]
@John-A-Davies This is actually the browser providing that dropdown history list, Unless we implemented our own history there's nothing we can do here.
