### ISSUE TITLE
Query for the DD statements fails if the JCL is closed with // (job end)

### ISSUE THREAD

**Issue by CindyZX** [zowe/explorer-jes#27]
If a JCL is ended with //, such as:

//INGJREXX PROC
//********************************************************************
//* *
//* ZOWE DEMO JCL *
//* *
//********************************************************************
//STEP1 EXEC PGM=IKJEFT01,TIME=1440,REGION=5M,
// PARM=‘HELLOW’
//SYSPROC DD DISP=SHR,DSN=PP.ING.SA.CLIST
//SYSTSPRT DD SYSOUT=*
//SYSTSIN DD DUMMY
//

query of https://HOSTNAME:PORT/api/v1/jobs/JOBNAME/ids/JOBINSTANCENAME/steps/STEPNUM/dds will fail with status code 500, error message is: java.lang.StringIndexOutOfBoundsException

**Comment by jordanCain** [comment]
@CindyZX we have taken the decision to remove steps from the jes explorer ui for the time being, the issue you have raised seems to be a problem with the explorer server therefore I have raised an issue there https://github.com/zowe/explorer-server/issues/26
