### ISSUE TITLE
Create fullscreen job spool viewer - single spool file

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/explorer-jes#4]
**As a** zowe user,  
**I want** a seperate URL to directly view my job information  
**so that** I can easily share the link with other people.

*Details/notes*  
We should create the separate URI for full screen job info, and add a copy link button to the JES explorer main page (separate story?).

To reference spool files by name would be much easier, but it is possible to have repeating, so we'll probably need to use id.

#### Acceptance Criteria

**Scenario 1:** Full screen job viewer for single spool file  
*Given* I have a job id *JJJ* with files *FFF (id FF1)* and *SSS (id SS1) *  
*When* I visit \<atlas URL>/explorer-jes/#/viewer?jobid=JJJ&file=FFF eg https://winmvs3b.hursley.ibm.com:7443/explorer-jes/#/viewer?jobid=STC12052&file=JESJCL  
*Then* I see a full page job viewer with the jobname, job id, spool file name and file content

**Comment by jordanCain** [comment]
Full screen jes viewer is provided and delivered in 0.9.1 https://github.com/zowe/explorer-jes/pull/7 

Release notes content - "
A full-screen job output view is now available. You can view a single job output file in a full-screen text area, which removes the need to navigate via the job tree. Note that this view is currently only available via direct access to the explorer. It is not accessible via the Zowe Desktop app in this release. To open a file in full screen, you can use the following URL/parameters:
https://host:explorerSecurePort/explorer-jes/#/?jobName=SAMPLEJOB&jobId=JOB12345&fileId=102"

Work still outstanding to create a button to jump out to fullscreen whilst viewing a file

**Comment by jordanCain** [comment]
Have raised #40 to cover the outstanding work here
