### ISSUE TITLE
After JES Explorer is started, the owner is pre-filled with {"username":"TSTRADM"}

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/explorer-jes#51]
With build 405, after JES Explorer is started, the owner field is pre-filled with `{"username":"TSTRADM"}`.

Here is screenshot:

![firefox_60 4 0_darwin_test-02-jes-explorer_001_app-loaded](https://user-images.githubusercontent.com/39711029/51212297-22fc1000-18e6-11e9-9217-bcf223107df6.png)

**Comment by stevenhorsman** [comment]
Fixed by https://github.com/zowe/explorer-jes/pull/52
