### ISSUE TITLE
Job Filters for non-existing Job ID does not work

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/explorer-jes#54]
With Zowe build 414 (also see similar issue on v0.9.5):

In Job Filters, when I use a Job ID that does not exist in SDSF, 
Owner=IBMUSER,
Prefix=*
Job ID=JOB07144 (non-existing Job)
It is trying and trying to locate the job, and it seems it is in a loop to find that. I expect to have an empty page that shows no result.
Response URL: https://tvt7050.svl.ibm.com:7554/api/v1/jobs?owner=IBMUSER&prefix=*

**Comment by jordanCain** [comment]
As part of receiving no jobs we should set the isFetching flag to false which will stop the icon from spinning

**Comment by jordanCain** [comment]
related: https://github.com/zowe/explorer-jes/issues/33

**Comment by jordanCain** [comment]
Have verified in build 449 and onwards this is fixed
