### ISSUE TITLE
Unable to load page on adding unknown url query parameter

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/explorer-jes#84]
Adding URL query param other than owner,prefix, jobId, and status, breaks in react, see console screenshot below.  Tried adding **key "noparam" with value "noValue"**, result in breaking.

![image](https://user-images.githubusercontent.com/4791635/53754279-753ac580-3e81-11e9-8000-f30cab4182e4.png)

**Comment by jordanCain** [comment]
This has been resolved by https://github.com/zowe/explorer-jes/pull/98
